### ISSUE TITLE
Evaluation errors missing context while syntax errors have them

### ISSUE THREAD

**Issue by colindean** [caketop/python-starlark-go#142]
When I encounter an evaluation error, I am not given any context, e.g. method name, line, etc.

```
$ python3 test.py .vela.star 
Traceback (most recent call last):
  File "/Users/colin/Source/myproject/python-poetry/test.py", line 10, in <module>
    print(s.eval("main([])"))
starlark_go.errors.EvalError: unknown binary op: NoneType | dict
```

I am given this information for syntax errors:
```
$ python3 test.py .vela.star 
Traceback (most recent call last):
  File "/Users/colin/Source/myproject/python-poetry/test.py", line 8, in <module>
    s.exec(input_file.read())
starlark_go.errors.ResolveError: <expr>:140:1: if statement not within a function
```

Perhaps the user can be given the context.

**Comment by jordemort** [comment]
If you catch the EvalError, is there anything in the .backtrace property? That should map to https://pkg.go.dev/go.starlark.net@v0.0.0-20230122040757-066229b0515d/starlark#EvalError.Backtrace

**Comment by colindean** [comment]
Yes! 

```python
from starlark_go.errors import EvalError
try:
    print(s.eval("main([])"))
except EvalError as e:
    print(e.backtrace)
```

produces

```
$ python3 test.py .vela.star 
Traceback (most recent call last):
  <expr>:1:5: in <expr>
  <expr>:143:10: in main
Error: unknown binary op: NoneType | dict
```

when I inject an error. I fixed the original error; there was a missing return statement ;-)

Could the top of that stack be added to the EvalError message text?

**Comment by jordemort** [comment]
Probably, it looks like [EvalError](https://pkg.go.dev/go.starlark.net@v0.0.0-20230122040757-066229b0515d/starlark#EvalError) exposes a [CallStack](https://pkg.go.dev/go.starlark.net@v0.0.0-20230122040757-066229b0515d/starlark#CallStack) full of [CallFrames](https://pkg.go.dev/go.starlark.net@v0.0.0-20230122040757-066229b0515d/starlark#CallFrame), each of which has a [syntax.Position](https://pkg.go.dev/go.starlark.net@v0.0.0-20230122040757-066229b0515d/syntax#Position).

We would probably want to add `function_name`, `line`, and `column` members to the Python [EvalError](https://github.com/caketop/python-starlark-go/blob/main/src/starlark_go/errors.py#L79), add additional parameters to hold them to the [C wrapper for its constructor](https://github.com/caketop/python-starlark-go/blob/main/starlark.c#L424), and then populate them from either the first or the last CallFrame [when an EvalError is raised](https://github.com/caketop/python-starlark-go/blob/main/python_exceptions.go#L51). Not sure what the right thing to do would be if the CallStack is empty, probably just "unknown", 0, 0.
